services:
  backend:
    build: ./backend
    container_name: cryptool-backend
    ports:
      - "8080:8080"
  frontend:
    build: ./frontend
    container_name: cryptool-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
